package com.hishark.tech.extension;

import java.util.List;

import org.eclipse.jdt.core.dom.AST;

import org.eclipse.jdt.core.dom.Javadoc;
import org.eclipse.jdt.core.dom.TagElement;
import org.eclipse.jdt.core.dom.TypeDeclaration;
import org.eclipse.uml2.uml.Class;
import org.eclipse.uml2.uml.Property;
import org.eclipse.uml2.uml.Stereotype;
import org.eclipse.uml2.uml.Type;

import com.ibm.xtools.transform.core.ITransformContext;

public class ApplyProfile extends
		com.ibm.xtools.transform.uml2.impl.internal.java5.ClassRule {

	@Override
	public boolean isSourceConsumed(ITransformContext context) {
		Class source = (Class) context.getSource();
		List list = source.getAppliedStereotypes();
		return list.size() != 0;
	}

	@Override
	public boolean canAccept(ITransformContext context) {
		return true;
	}

	@Override
	public Object createTarget(ITransformContext context) {
		TypeDeclaration target = (TypeDeclaration) context.getTarget();
		Javadoc doc = target.getJavadoc();
		AST ast = target.getAST();

		List tags = doc.tags();
		TagElement tag = ast.newTagElement();

		tag.setTagName("This is generated by Shark");
		tags.add(tag);

		Class source = (Class) context.getSource();
		Stereotype stereotype = source.getAppliedStereotype("Profile::ModelHelper");
		Property pro= stereotype.getAttribute("implClass", null);
		String supperC= pro.getDefault();
		
		target.setSuperclassType(ast.newSimpleType(ast
				.newName(supperC)));

		return target;
	}

}
