all:
  children:
    nix:
      children:
        mac:
          hosts:
            localhost:
          vars:
            ansible_connection: local
        linux:
          hosts:
    #        192.168.31.128:
          vars:
            ansible_user: shark
            ansible_become_password: shark
    win:
      hosts:
#        192.168.31.112:
#        192.168.31.103:
#        192.168.31.128:
      vars:
        ansible_user: shark
        ansible_shell_type: cmd
